apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    run: subscription-service
spec:
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
  type: NodePort
  selector:
    run: subscription